### ISSUE TITLE
service vitam-access-external KO à l'installation (problème keystore)

### ISSUE THREAD

**Issue by bxaxa** [ProgrammeVitam/vitam#11]
contexte: Instance scaleway, 16Go RAM, 8Core, 50Gb DD, Debian Stretch.

Hello,
  je suis en train de tenter l'installation 3 VMs (small). Tout se passe bien jusqu'au test du service vitam-access-external. Il ne démarre pas.

> Erreur du playbook au moment du déploiement.

```
TASK [vitam : Check if vitam-access-external is listening on service port 8444] **************************************************

fatal: [small-vm-1]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 10.5.74.187:8444"}

NO MORE HOSTS LEFT ***************************************************************************************************************

PLAY RECAP ***********************************************************************************************************************
small-vm-1                 : ok=170  changed=89   unreachable=0    failed=1    skipped=94   rescued=0    ignored=0
small-vm-2                 : ok=270  changed=137  unreachable=0    failed=0    skipped=131  rescued=0    ignored=1
small-vm-3                 : ok=145  changed=84   unreachable=0    failed=0    skipped=67   rescued=0    ignored=0

```

Effectivement rien n'écoute sur 8444

> Les logs du service acces-external 

`cat access-external.2019-07-30.0.log`

```
2019-07-30 16:18:42,539 [[main]] [] WARN  fr.gouv.vitam.common.serverv2.application.CommonBusinessApplication - Caller+1         at fr.gouv.vitam.common.serverv2.application.CommonBusinessApplication.clearAndconfigureMetrics(CommonBusinessApplication.java:111) : [vitam-zone-1:access-external:185284261] No content to map due to end-of-input
 at [Source: (FileInputStream); line: 23, column: 1]
2019-07-30 16:18:42,562 [[main]] [] WARN  fr.gouv.vitam.common.metrics.VitamMetrics - Caller+1   at fr.gouv.vitam.common.metrics.VitamMetrics.<init>(VitamMetrics.java:88) : [vitam-zone-1:access-external:185284261] VitamMetrics instanciated without reporter.
2019-07-30 16:18:48,446 [[main]] [] ERROR fr.gouv.vitam.access.external.rest.AccessExternalMain - Caller+1       at fr.gouv.vitam.access.external.rest.AccessExternalMain.main(AccessExternalMain.java:111) : [vitam-zone-1:access-external:185284261] access-external application server can not start. A problem occurred while attempting to start the server java.lang.IllegalStateException: no valid keystore
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:50)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1194)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:334)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:256)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:94)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:282)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:396)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at fr.gouv.vitam.common.server.BasicVitamServer.start(BasicVitamServer.java:157)
        ... 4 common frames omitted
Wrapped by: fr.gouv.vitam.common.exception.VitamApplicationServerException: A problem occurred while attempting to start the server
        at fr.gouv.vitam.common.server.BasicVitamServer.start(BasicVitamServer.java:159)
        at fr.gouv.vitam.common.server.BasicVitamServer.startAndJoin(BasicVitamServer.java:138)
        at fr.gouv.vitam.common.serverv2.VitamStarter.run(VitamStarter.java:317)
        at fr.gouv.vitam.access.external.rest.AccessExternalMain.startAndJoin(AccessExternalMain.java:132)
        at fr.gouv.vitam.access.external.rest.AccessExternalMain.main(AccessExternalMain.java:109)

```

**Comment by croftophile** [comment]
Bonsoir,
Les stores sont générés soir par "vous", soit par la PKI de tests fournie avec Vitam. Quel cas avez-vous utilisé ? Les vault ansible reflètent-t-ils bien ce que vous comptiez installer ?
Quelles sont les versions (sur serveur de déploiement comme les serveurs vitam) des packages openssl et Java ?
Quelle est la version de gawk sur le serveur de déploiement ?

**Comment by bxaxa** [comment]
Bonjour, 
  c'est ma faute, j'ai zappé une étape : generate_stores.sh

A ma décharge, cette étape n'est pas clairement identifié dans le déploiement d'une plateforme de recette.

Peut-être serait-il utile d'y faire référence sur cette page de la documentation:

https://www.programmevitam.fr/ressources/DocCourante/html/installation/installation/certificats/pki_vitam.html

Je clos l'issue car elle n'à plus lieu d'être. 

Merci.
