### ISSUE TITLE
Usage de la VM de test

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#18]
Bonjour,
Lorsque je veux utiliser la VM de test, en suivant la procédure décrite (import du référentiel des règles, des services agents, des contrats d'accès, d'entrées) dans le tenant 9, tout se passe correctement.
Mais lorsque je veux réaliser une entrée (en utilisant le fichier du Jeu_de_tests_Guide_de_prise_en_main), j'ai une croix en résultat et aucune information dans les journaux.
En allant voir dans les logs de Ingest External, j'obtiens ceci:

     2019-09-10 07:44:36,654 [[vitam-thread-98]] [aeeaaaaabghqjh74abb72alndiq2p7qaaaaq] ERROR fr.gouv.vitam.security.internal.filter.InternalSecurityFilter - 
    Caller+1	 at fr.gouv.vitam.security.internal.filter.InternalSecurityFilter.filter(InternalSecurityFilter.java:164) : [vitam-demo:ingest-external:251961340] Security Error : 
     fr.gouv.vitam.security.internal.exception.VitamSecurityException: Ingest contract not found in the context for the tenant id :9
	at fr.gouv.vitam.security.internal.filter.InternalSecurityFilter.verifyIngestContract(InternalSecurityFilter.java:241)
	at fr.gouv.vitam.security.internal.filter.InternalSecurityFilter.filter(InternalSecurityFilter.java:151)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:305)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at fr.gouv.vitam.common.tenant.filter.TenantFilter.doFilter(TenantFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at fr.gouv.vitam.common.thread.VitamThreadPoolExecutor$VitamRunnable.run(VitamThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Pouvez-vous m'indiquer ce qui se passe, vu que le contrat d'entrée (et d'accès sélectionné en haut) sont bien ceux que j'ai importés dans le tenant 9, tenant dans lequel je me situe toujours?

Bien à vous,
Frédéric
(Je joins quelques pdf des référentiels pour aider)
[contexteadmin.pdf](https://github.com/ProgrammeVitam/vitam/files/3594459/contexteadmin.pdf)
[contextes.pdf](https://github.com/ProgrammeVitam/vitam/files/3594460/contextes.pdf)
[contrat-acces.pdf](https://github.com/ProgrammeVitam/vitam/files/3594461/contrat-acces.pdf)
[Uploading contrat-entrée.pdf…]()
[Uploading règles.pdf…]()

**Comment by fredericBregier** [comment]
J'utilise l'IHM Demo avec le compte aadmin...

**Comment by fredericBregier** [comment]
NB: si je me déconnecte (de l'IHM), Vitam ne répond plus et je dois le relancer, mais c'est un autre problème...

**Comment by fredericBregier** [comment]
Version 2.6.3-1 (j'avais oublié de le préciser), dans une VM sous VirtualBox 6.0.12 sous Ubuntu, avec 8 Go de mémoire allouée, 2 processeurs.

**Comment by fredericBregier** [comment]
(NB: pour relancer Vitam, je n'ai d'autre choix que de relancer la VM, les restart vitam-demo ou vitam-consul ne change rien)

**Comment by fredericBregier** [comment]
NB: Vitam ne s'arrête pas, c'est l'interface réseau... Erreur du network.service: Failed to start LSB
En relançant NetworkService, c'est tout bon.

Reste le pbl d'ingest qui ne passe pas pour un contrat inconnu alors que bien présent... ?

**Comment by naddame** [comment]
Bonjour Frederic,

Il ya un check de sécurité dans le filter InternalSecurityFilter:  Il vérifie que le contrat d'entrée et/ou d'accès sont bien déclarés dans le contexte et dans le tenant qui va bien (tenant 9 dans ce cas).

D'après le fichier contexteadmin.pdf (qui correspond au certificats par défaut), le tenant 9 ne contient pas de contrat et donc le filtre rejette la requête.

Veuillez ajouter les contrats dans le contexte tenant 9 et re-essayer.

**Comment by fredericBregier** [comment]
C'est bien pour cela que j'ai imprimé cette page, car dans les contextes, seul Admin est actif et il n'a rien sur le tenant 9.
Mais quand je vais dans l'Administration, Référentiel, le contrat d'ingest y est bien (celui proposé par la procédure Jeu_de_tests_Guide_de_prise_en_main), comme le montre la copie PDF.

Elle semble ne pas s'être chargé dans mon post initial: (comme pour les règles)
[contrat-entrée.pdf](https://github.com/ProgrammeVitam/vitam/files/3594985/contrat-entree.pdf)
[règles.pdf](https://github.com/ProgrammeVitam/vitam/files/3594987/regles.pdf)

Les voici...
J'ai donc bien les règles, les services, les contrats d'accès et les contrats d'entrée chargés dans le tenant 9. J'ai essayé aussi avec le tenant 2, idem, même résultat.
L'erreur est toujours la même.
Une idée ?

**Comment by naddame** [comment]
Sur le tenant 1, il faut éditer le contexte d'admin pour :
- Soit ajouter pour le tenant voulu les identifiers des contrats. Dans votre cas le contrat d'entrée, mais ensuite pour accéder aux AU il faut aussi rajouter le contrat d'accès.
- Soit mettre le champs "Activation des permissions" à inactif

Sans l'une de ces deux modifications, le filter InternalSecurityFilter rejettera la requête

**Comment by fredericBregier** [comment]
Merci ! Cela a fonctionné avec la deuxième option.
En effet, la première ne fonctionne pas (l'interface d'administration en mode modification refuse d'enregistrer les ajouts de contrats sur le tenant 9 avec une erreur sans explication).
Par contre, la modification de l'activation des permissions fonctionne. 

Pourquoi l'une et pas l'autre ? Je ne sais pas.

Peut-être faudrait-il ajouter ce cas dans les how to, s'il n'y est pas déjà pour expliquer quoi faire ? (notamment dans le manuel de mise en oeuvre)

Cependant, une erreur plus explicite sans aller dans les logs serait intéressante. Là, je savais où chercher, et j'avais compris l'erreur, mais je ne voyais pas quoi faire pour corriger.

La correction ici est plus un hack qu'autre chose, vu qu'il n'y a plus aucune vérification. Pour mes tests, ça va, mais pour une expérimentation plus lourde, cela serait gênant.

Je vais essayer de noter mes aléas dans un fichier et vous le transmettre via Github pour mémoire.
Bien à vous,
Frédéric
