### ISSUE TITLE
Regression 3.0.1 vs 2.15.3: client external : impossibilité d'upgrade

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#39]
Pour la régression 1 constatée: confirmée

Cette erreur n'arrive pas en 2.15.3, mais arrive en 3.0.1:

    13:19:05.212 [IngestManager-1] WARN org.waarp.vitam.ingest.IngestManager - org.waarp.vitam.ingest.IngestManager.getStatusOfATR(IngestManager.java:542) : Issue since ingest client produces an error
    fr.gouv.vitam.common.exception.VitamClientException: fr.gouv.vitam.ingest.external.api.exception.IngestExternalClientServerException
	at fr.gouv.vitam.ingest.external.client.IngestExternalClientRest.downloadObjectAsync(IngestExternalClientRest.java:128)
	at org.waarp.vitam.ingest.IngestManager.getStatusOfATR(IngestManager.java:519)
	at org.waarp.vitam.ingest.IngestManager.runStep(IngestManager.java:338)
	at org.waarp.vitam.ingest.IngestManager.run(IngestManager.java:286)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: fr.gouv.vitam.ingest.external.api.exception.IngestExternalClientServerException: null
	at fr.gouv.vitam.ingest.external.client.IngestExternalClientRest.check(IngestExternalClientRest.java:188)
	at fr.gouv.vitam.ingest.external.client.IngestExternalClientRest.downloadObjectAsync(IngestExternalClientRest.java:125)
	... 6 common frames omitted

Cause probable:

- https://github.com/ProgrammeVitam/vitam/commit/165aeb588b3fe432b2607ba080a7af900fcb18d7#diff-ea6d6c4758da9bfec23550c434768e81
- https://github.com/ProgrammeVitam/vitam/commit/d91f94464f00a2fb012771a1e6728920435315c3#diff-ea6d6c4758da9bfec23550c434768e81

où le code async a été changé en profondeur...

**Comment by fredericBregier** [comment]
Pour la régression 2 constatée : confirmée

Cette erreur n'arrive pas en 2.15.3, mais arrive en 3.0.1:

    13:28:54.526 [pool-1-thread-1] ERROR fr.gouv.vitam.common.retryable.Retryable - [frederic-X510UQ:UnknownRole:42087724] [frederic-X510UQ:UnknownRole:42087724] Retryable='fr.gouv.vitam.common.external.client.AbstractCommonClient$$Lambda$148/0x0000000840375840@ab3b448' - Will retry, attempt '1' in '1' SECONDS. javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8189 [localhost/127.0.0.1] failed: Connexion refusée (Connection refused)
	at fr.gouv.vitam.common.external.client.VitamApacheHttpClientEngine.invoke(VitamApacheHttpClientEngine.java:329)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:439)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:61)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.method(ClientInvocationBuilder.java:297)
	at fr.gouv.vitam.common.external.client.AbstractCommonClient.lambda$doRequest$1(AbstractCommonClient.java:195)
	at fr.gouv.vitam.common.retryable.RetryableOnException.exec(RetryableOnException.java:65)
	at fr.gouv.vitam.common.external.client.AbstractCommonClient.doRequest(AbstractCommonClient.java:201)
	at fr.gouv.vitam.common.external.client.AbstractCommonClient.make(AbstractCommonClient.java:171)
	at fr.gouv.vitam.common.external.client.DefaultClient.make(DefaultClient.java:34)
	at fr.gouv.vitam.access.external.client.AdminExternalClientRest.getOperationProcessStatus(AdminExternalClientRest.java:674)
	at fr.gouv.vitam.access.external.client.VitamPoolingClient.wait(VitamPoolingClient.java:79)
	at fr.gouv.vitam.access.external.client.VitamPoolingClient.wait(VitamPoolingClient.java:144)
	at org.waarp.vitam.common.OperationCheck.checkAvailabilityAtr(OperationCheck.java:135)
	at org.waarp.vitam.common.OperationCheck.main(OperationCheck.java:110)
	at org.waarp.vitam.dip.DipTaskTest.givenErrorWhenCheckKO(DipTaskTest.java:436)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:362)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8189 [localhost/127.0.0.1] failed: Connexion refusée (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at fr.gouv.vitam.common.external.client.VitamApacheHttpClientEngine.invoke(VitamApacheHttpClientEngine.java:279)
	... 48 more
    Caused by: java.net.ConnectException: Connexion refusée (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 56 more


Plus difficile à trouver la source, mais sans doute similaire à celle de Ingest.

**Comment by TDevillechabrolle** [comment]
Bonjour Frédéric,

Désolé pour cette remonté tardive, nous analysons votre issue.
Trois petites questions:
- Je crois comprendre que deux problèmes, du même type, sont soulevés dans l'issue. Si c'est bien le cas, pour des raisons de gestion du suivi il serait préférable à l'avenir d'ouvrir une issue pour chaque problème.
- Avez-vous le moyen de fournie la réponse avec le client 2.15.3 ?
- Dans le deuxième log, il est fait mention d'un problème de connexion à localhost:8189
Pouvez-vous nous indiquer à quel service correspond ce port, svp ?

Bonne journée,
Thierry

**Comment by fredericBregier** [comment]
See #41  and #42 for separation @TDevillechabrolle
