### ISSUE TITLE
Redémarrage installation Docker ne fonctionne plus 

### ISSUE THREAD

**Issue by pierrickmolera** [ProgrammeVitam/vitam#65]
Bonjour,
j'ai installé la dernière version du Programme Vitam avec l'environnement Docker.
Tout s'est très bien passé, tous les services sont démarrés et je peux utiliser et tester des premiers versements SIP avec l'application ihm-demo.

Cependant après l'arrêt de ma machine et donc du conteneur, après le redémarrage de ce conteneur tous les services ne sont pas démarrés.
J'ai ensuite testé la commande vitam-restart à l'intérieur du conteneur et le script s'arrête au démarrage du service vitam-elacticsearch-data avec un timeout sur le port 9200.
Merci par avance.

**Comment by gansheer** [comment]
Bonjour,

Avez-vous vérifié les logs de l'elasticsearch-data ? D'expérience le timeout indique qu'il n'arrive pas à se lancer.

Vous pouvez tout d'abord vérifier l'état du service : `systemctl status vitam-elasticsearch-data`.
Ensuite s'il n'y a pas assez de détail vous pouvez également regarder les logs qui sont présents dans le dossier : `/vitam/log/elatsicsearch-data`.

Cordialement,

**Comment by pierrickmolera** [comment]
Merci pour votre réponse,
Avec les logs je n'ai pas beaucoup d'élément de réponse : 
La commande suivante  sudo systemctl status vitam-elasticsearch-data 
me donne ceci :

``` * vitam-elasticsearch-data.service - Elasticsearch-data
   Loaded: loaded (/lib/systemd/system/vitam-elasticsearch-data.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-10-20 10:28:13 UTC; 4h 16min ago
    Docs: http://www.elastic.co
 Process: 22885 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 22885 (code=exited, status=1/FAILURE)

Oct 20 10:28:13 75d7a4a774e7 elasticsearch[22885]:         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
Oct 20 10:28:13 75d7a4a774e7 elasticsearch[22885]:         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
Oct 20 10:28:13 75d7a4a774e7 elasticsearch[22885]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
Oct 20 10:28:13 75d7a4a774e7 elasticsearch[22885]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
Oct 20 10:28:13 75d7a4a774e7 elasticsearch[22885]:         at org.elasticsearch.cli.Command.main(Command.java:90)
Oct 20 10:28:13 75d7a4a774e7 elasticsearch[22885]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
Oct 20 10:28:13 75d7a4a774e7 elasticsearch[22885]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Oct 20 10:28:13 75d7a4a774e7 elasticsearch[22885]: For complete error details, refer to the log at /vitam/log/elasticsearch-data/elasticsearch-data.log
Oct 20 10:28:13 75d7a4a774e7 systemd[1]: vitam-elasticsearch-data.service: Main process exited, code=exited, status=1/FAILURE
Oct 20 10:28:13 75d7a4a774e7 systemd[1]: vitam-elasticsearch-data.service: Failed with result 'exit-code'.
```
L'affichage des logs /vitam/log/elasticsearch-data/elasticsearch-data.log : 
```
[2020-10-19T07:46:17,655][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][41770] overhead, spent [477ms] collecting in the last [1s]
[2020-10-19T07:59:59,895][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][42589] overhead, spent [389ms] collecting in the last [1.2s]
[2020-10-19T08:05:15,936][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][42904] overhead, spent [340ms] collecting in the last [1s]
[2020-10-19T08:17:03,057][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][43609] overhead, spent [311ms] collecting in the last [1s]
[2020-10-19T09:19:13,194][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][47328] overhead, spent [291ms] collecting in the last [1s]
[2020-10-19T10:38:19,387][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][52060] overhead, spent [280ms] collecting in the last [1s]
[2020-10-19T11:00:45,054][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][53401] overhead, spent [347ms] collecting in the last [1s]
[2020-10-19T11:20:59,597][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][54612] overhead, spent [518ms] collecting in the last [1.5s]
[2020-10-19T11:51:01,266][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][56407] overhead, spent [274ms] collecting in the last [1s]
[2020-10-19T11:59:17,785][INFO ][o.e.x.s.SnapshotRetentionTask] [localhost] starting SLM retention snapshot cleanup task
[2020-10-19T12:10:22,758][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][57565] overhead, spent [492ms] collecting in the last [1s]
[2020-10-19T12:19:45,006][WARN ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][58126] overhead, spent [526ms] collecting in the last [1s]
[2020-10-19T12:27:28,733][WARN ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][58588] overhead, spent [512ms] collecting in the last [1s]
[2020-10-19T12:31:50,800][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][58849] overhead, spent [334ms] collecting in the last [1s]
[2020-10-19T12:44:07,573][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][59584] overhead, spent [484ms] collecting in the last [1s]
[2020-10-19T12:46:42,032][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][59738] overhead, spent [479ms] collecting in the last [1s]
[2020-10-19T13:19:37,373][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][61705] overhead, spent [509ms] collecting in the last [1.4s]
[2020-10-19T13:42:06,399][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][63050] overhead, spent [324ms] collecting in the last [1s]
[2020-10-19T14:59:26,637][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][67675] overhead, spent [385ms] collecting in the last [1.3s]
[2020-10-19T15:01:14,929][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][67783] overhead, spent [264ms] collecting in the last [1s]
[2020-10-19T15:18:55,001][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][68840] overhead, spent [299ms] collecting in the last [1s]
[2020-10-19T15:47:32,889][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][70552] overhead, spent [482ms] collecting in the last [1s]
[2020-10-19T16:00:00,924][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][71298] overhead, spent [292ms] collecting in the last [1s]
[2020-10-19T16:00:16,502][INFO ][o.e.m.j.JvmGcMonitorService] [localhost] [gc][71313] overhead, spent [561ms] collecting in the last [1.1s]
```

**Comment by pierrickmolera** [comment]
Je cherche  toujours et j'ai passé en revue plusieurs points :
 - j'ai suffisamment de ressources par rapport à ce qui est paramétré dans la JVM
- j'ai qq doutes sur les chemins vitam/ log, tmp, bin etc... et les droits associés. Je n'ai rien touché à ce niveau-là mais tout est associé aux utilisateurs vitam ou vitamdb. j'espère qu'il n'y a pas de blocage. De mon côté la session de la machine host est bien exécutée avec un utilisateur non root. Côté conteneur j'ai laissé tel quel.
- Installation ElasticSearch ok, ça a démarré la première fois sans problèmes.

**Comment by TDevillechabrolle** [comment]
Bonjour,
Si vous êtes toujours sur le sujet, pourriez-vous nous indiquer la taille mémoire allouée à Elastic ?

**Comment by pierrickmolera** [comment]
Bonjour,
oui j'ai toujours mon environnement VITAM conteunarisé de côté.
La machine virtuelle dans laquelle était exécuté le conteneur posséde 8 Go de RAM et par rapport à la configuration d'ES je n'ai rien modifié, j'ai laissé ce qui était automatiquement configuré et installé.
ES a bien fonctionné une première fois, par la suite  il restait toujours de la marge niveau ressource.
Sinon j'ai vu que vous aviez une VM déjà préinstallée, aussi je pense l'utiliser pour tester le programme Vitam.

**Comment by TDevillechabrolle** [comment]
Je me permets de fermer le sujet ouvert depuis un moment.
Bien sûr, si besoin, il peut être réouvert.
